### ISSUE TITLE
Feature request: Save Text File - File Name as Output

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [YMC-GitHub/ymc-node-suite-comfyui#1]
Would it be possible to get the final file name, including the filename_delimiter, and filename number padding as output for the node?

![image](https://github.com/YMC-GitHub/ymc-node-suite-comfyui/assets/60541708/b41be7c2-f763-4cb9-b867-ba6c9f1f8826)

It would be very helpful to be able to match the output image name to a saved text file. I'm trying to generate captions for the generated images right from comfy.

**Comment by MNeMoNiCuZ** [comment]
I updated the code with some help from ChatGPT. It's not perfect. I couldn't get it to only return one string, so it returns 2 right now. But it works.
```
# set INPUT_TYPES
class WAS_Text_Save:
    def __init__(self):
        pass

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "text": ("STRING", {"forceInput": True}),
                "path": ("STRING", {"default": './output/[time(%Y-%m-%d)]/', "multiline": False}),
                "filename_prefix": ("STRING", {"default": "ComfyUI"}),
                "filename_delimiter": ("STRING", {"default":"_"}),
                "filename_number_padding": ("INT", {"default":4, "min":2, "max":9, "step":1}),
                "overwrite_mode": (["false", "prefix_as_filename"],),
            }
        }

    OUTPUT_NODE = True
    RETURN_TYPES = ("STRING", "STRING")
    FUNCTION = "save_text_file"
    CATEGORY = "Ymc Suite/IO"

    def save_text_file(self, text, path, filename_prefix='ComfyUI', filename_delimiter='_', filename_number_padding=4, overwrite_mode='false'):
    
        tokens = TextTokens()
        path = tokens.parseTokens(path)
        filename_prefix = tokens.parseTokens(filename_prefix)
    
        if not os.path.exists(path):
            cstr(f"The path `{path}` doesn't exist! Creating it...").warning.print()
            try:
                os.makedirs(path, exist_ok=True)
            except OSError as e:
                cstr(f"The path `{path}` could not be created! Is there write access?\n{e}").error.print()

        if text.strip() == '':
            cstr(f"There is no text specified to save! Text is empty.").error.print()

        
        delimiter = filename_delimiter
        number_padding = int(filename_number_padding)
        file_extension = '.txt'

        filename, counter = self.generate_filename(path, filename_prefix, delimiter, number_padding, file_extension)
        if overwrite_mode == 'prefix_as_filename':
            filename = f"{filename_prefix}{file_extension}"
        file_path = os.path.join(path, filename)

        output_path = f"{filename_prefix}{delimiter}{str(counter).zfill(number_padding)}"

        self.writeTextFile(file_path, text)

        update_history_text_files(file_path)

        return text, output_path
        
    def generate_filename(self, path, prefix, delimiter, number_padding, extension):
        pattern = f"{re.escape(prefix)}{re.escape(delimiter)}(\\d{{{number_padding}}})"
        existing_counters = [
            int(re.search(pattern, filename).group(1))
            for filename in os.listdir(path)
            if re.match(pattern, filename)
        ]
        existing_counters.sort(reverse=True)

        if existing_counters:
            counter = existing_counters[0] + 1
        else:
            counter = 1

        filename = f"{prefix}{delimiter}{counter:0{number_padding}}{extension}"
        return filename, counter

    def writeTextFile(self, file, content):
        try:
            with open(file, 'w', encoding='utf-8', newline='\n') as f:
                f.write(content)
        except OSError:
            cstr(f"Unable to save file `{file}`").error.print()
```


![image](https://github.com/YMC-GitHub/ymc-node-suite-comfyui/assets/60541708/f4ffa4d2-a6e8-47a6-a8bf-0712138a313c)

**Comment by YMC-GitHub** [comment]
well done. I'll merge as planned or you can fork one If you need it urgently.

**Comment by MNeMoNiCuZ** [comment]
Thanks!
I needed it for a workflow that I wanted to share, so I set up my own node pack (just this one so far).

https://github.com/MNeMoNiCuZ/ComfyUI-mnemic-nodes

It would be great to rename the output strings accordingly, and possibly output several versions, depending on what could be useful.

The resulting "filename number padding" value could be useful on its own. With this you can ensure that multiple files as outputs share name. Maybe an option or format for the output could work too?

Like have an Output Field option, that takes the names of the input attributes something like this:
[path][text][filename_delimiter][filename_number_padding]

And that would give you those attributes for the output?
Just a suggestion.

**Comment by YMC-GitHub** [comment]
I added it  in v1.1.0(28b0da0c9a447be969e1d4b12f05e1a3915109a1) :

the "filename number padding" use a String type, showed with name 'filenameWithoutExt' as 2th result.

it return "filename number padding"  when  overwrite_mode is 'false'.

it return  itself when overwrite_mode is 'prefix_as_filename'.
