### ISSUE TITLE
Doesn't work because of the comple dependencies

### ISSUE THREAD

**Issue by Cedri4** [YMC-GitHub/ymc-node-suite-comfyui#2]
Terminal error 
![image](https://github.com/YMC-GitHub/ymc-node-suite-comfyui/assets/93396286/0dee6b1c-6fd4-484f-9c46-0779229ea149)

**Comment by YMC-GitHub** [comment]
could you show more details? when you installing dependencies with this repo [requirements.txt](https://github.com/YMC-GitHub/ymc-node-suite-comfyui/blob/main/requirements.txt)?

**Comment by Cedri4** [comment]
Oh do I have to manually install the dependencies in requirements.txt ?

**Comment by Cedri4** [comment]
Device: cuda:0 NVIDIA GeForce GTX 1060 3GB : cudaMallocAsync
VAE dtype: torch.float32
Torch version: 2.0.1+cu118
### Loading: ComfyUI-Workflow-Component (V0.43.3) !! WARN: This is an experimental extension. Extremely unstable. !!
### Loading: Workspace Manager (V1.0.0)
------------------------------------------------
Comfyroll Custom Nodes v1.50 :  150 Nodes Loaded
------------------------------------------------
### [START] ComfyUI AlekPet Nodes ###
Node -> ArgosTranslateNode [Loading]
Node -> ExtrasNode [Loading]
Node -> PainterNode [Loading]
Node -> PoseNode [Loading]
Node -> TranslateNode [Loading]
### [END] ComfyUI AlekPet Nodes ###
Davemane42 Custom Nodes: Loaded
FizzleDorf Custom Nodes: Loaded
[smZNodes] compel is not installed. Attempting to install...
Collecting compel
  Using cached compel-2.0.2-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: diffusers>=0.11 in f:\stable-diffusion\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from compel) (0.23.0)
Requirement already satisfied: pyparsing~=3.0 in f:\stable-diffusion\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from compel) (3.0.9)
Requirement already satisfied: torch in f:\stable-diffusion\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from compel) (2.0.1+cu118)
Requirement already satisfied: transformers~=4.25 in f:\stable-diffusion\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from compel) (4.31.0)
Requirement already satisfied: importlib-metadata in f:\stable-diffusion\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from diffusers>=0.11->compel) (6.8.0)
Requirement already satisfied: filelock in f:\stable-diffusion\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from diffusers>=0.11->compel) (3.12.2)
Requirement already satisfied: huggingface-hub>=0.13.2 in f:\stable-diffusion\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from diffusers>=0.11->compel) (0.19.4)
Requirement already satisfied: numpy in f:\stable-diffusion\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from diffusers>=0.11->compel) (1.23.5)
Requirement already satisfied: regex!=2019.12.17 in f:\stable-diffusion\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from diffusers>=0.11->compel) (2023.8.8)
Requirement already satisfied: requests in f:\stable-diffusion\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from diffusers>=0.11->compel) (2.31.0)
Requirement already satisfied: safetensors>=0.3.1 in f:\stable-diffusion\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from diffusers>=0.11->compel) (0.3.2)
Requirement already satisfied: Pillow in f:\stable-diffusion\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from diffusers>=0.11->compel) (9.5.0)
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'f:\\stable-diffusion\\comfyui\\comfyui_windows_portable\\python_embeded\\lib\\site-packages\\transformers-4.31.0.dist-info\\METADATA'

[smZNodes] Failed to install compel.
Traceback (most recent call last):
  File "F:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1813, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes\__init__.py", line 48, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "F:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes\nodes.py", line 6, in <module>
    from .modules import prompt_parser, devices, shared
  File "F:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes\modules\prompt_parser.py", line 8, in <module>
    from compel import Compel
ModuleNotFoundError: No module named 'compel'

In the terminal

**Comment by YMC-GitHub** [comment]
1. installing the dependencies in requirements.txt  of this repo is optional. but recommended.
 2. This error you showed is not caused by the dependency of this repository (ymc-node-suite-comfyui).  do you know how to setup comfyui? and did you make comfyui running?

**Comment by YMC-GitHub** [comment]
it shows the dependce of 'compel' is not installed  which is required in 'ComfyUI_smZNodes'.

- 'ModuleNotFoundError: No module named 'compel'
- custom_nodes\ComfyUI_smZNodes\modules\prompt_parser.py", line 8, in

you need to install it in your python venv . eg. `pip install compel`

**Comment by Cedri4** [comment]
Oh, I think 2 weeks ago I misread the name of the GitHub repository, sorry.
