### ISSUE TITLE
Please rename your Image Save and Save Text File nodes

### ISSUE THREAD

**Issue by WASasquatch** [YMC-GitHub/ymc-node-suite-comfyui#3]
These nodes conflict with WAS Node Suite. You should be using custom_node standards and use the class name for the NODE_CLASS_MAPPINGS and a **safe name** for NODE_DISPLAY_NAME_MAPPINGS

WAS Node Suite was made before NODE_DISPLAY_NAME_MAPPINGS and doesn't use it. And for me to make my node suite compatible with yours, it means breaking everyone workflows back to basically the release of ComfyUI. It would make much more sense for  you to update your relatively new suite that isn't in thousands and thousands of workflows.

**Comment by YMC-GitHub** [comment]
I will update it right now.

**Comment by YMC-GitHub** [comment]
I put it in 5c689121534c51c650ddc244995d2d7783e2ce84
